### ISSUE TITLE
No linux support???

### ISSUE THREAD

**Issue by tarcom** [RobbingDaHood/TableSoccerREST#14]
The wiki states that a .bat file should be executed in order to start the server, thats a tad unambiguous, espically if I should have the thing running on my amazon elastic cloud which runs linux :(

Ill see if I can figure out a way of running the thing on linux, but it would be nice with a default setup that is platform independent :D

**Comment by tarcom** [comment]
Cant get gradle to build, this is my output:


ubuntu@ip-172-31-36-90:~/dwpRest/TableSoccerREST$ gradle build

FAILURE: Build failed with an exception.

* Where:
Build file '/home/ubuntu/dwpRest/TableSoccerREST/build.gradle' line: 3

* What went wrong:
A problem occurred evaluating root project 'TableSoccerREST'.
> Could not find method jcenter() for arguments [] on repository container.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.197 secs

**Comment by RobbingDaHood** [comment]
Just run: ./gradlew run 
in the root. 

It were always there and I just updated the wiki. 

Tell me if that works for you?

**Comment by tarcom** [comment]
Thanks, now it works.... well, and then again:



[main] INFO ratpack.server.RatpackServer - Starting server...
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00007ffb576e7000, 262144, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 262144 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /home/ubuntu/dwpRest/TableSoccerREST/hs_err_pid32166.log
:run FAILED

**Comment by tarcom** [comment]
But now it builds on jenkins :)

http://35.164.183.35:8081/job/TableSoccerREST%20at%20github/

**Comment by tarcom** [comment]
After a restart it all compiles and runs smoothly!!! Nice api :)

http://35.164.183.35:5050/api
